spring:
  application:
    name: cobranca-config-server
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
cobranca-config-serve:
   greeting: "Ol√°"
   default-value: "Mundo"
